/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const EDITOR_THEME_MAP: typeof import('./hooks/use-editor').EDITOR_THEME_MAP
  const Fragment: typeof import('react').Fragment
  const IHugeiconsAlert02: typeof import('~icons/hugeicons/alert02.jsx').default
  const IHugeiconsArrowDown01: typeof import('~icons/hugeicons/arrow-down01.jsx').default
  const IHugeiconsArrowLeft02: typeof import('~icons/hugeicons/arrow-left02.jsx').default
  const IHugeiconsArrowRight01: typeof import('~icons/hugeicons/arrow-right01.jsx').default
  const IHugeiconsArrowRight02: typeof import('~icons/hugeicons/arrow-right02.jsx').default
  const IHugeiconsBookOpen01: typeof import('~icons/hugeicons/book-open01.jsx').default
  const IHugeiconsCode: typeof import('~icons/hugeicons/code.jsx').default
  const IHugeiconsCopy01: typeof import('~icons/hugeicons/copy01.jsx').default
  const IHugeiconsHelpCircle: typeof import('~icons/hugeicons/help-circle.jsx').default
  const IHugeiconsKeyboard: typeof import('~icons/hugeicons/keyboard.jsx').default
  const IHugeiconsLayers01: typeof import('~icons/hugeicons/layers01.jsx').default
  const IHugeiconsMessageQuestion: typeof import('~icons/hugeicons/message-question.jsx').default
  const IHugeiconsReload: typeof import('~icons/hugeicons/reload.jsx').default
  const IHugeiconsSearch01: typeof import('~icons/hugeicons/search01.jsx').default
  const IHugeiconsSettings02: typeof import('~icons/hugeicons/settings02.jsx').default
  const IHugeiconsShield01: typeof import('~icons/hugeicons/shield01.jsx').default
  const IHugeiconsSparkles: typeof import('~icons/hugeicons/sparkles.jsx').default
  const IHugeiconsStructure03: typeof import('~icons/hugeicons/structure03.jsx').default
  const IHugeiconsSun02: typeof import('~icons/hugeicons/sun02.jsx').default
  const IHugeiconsTick02: typeof import('~icons/hugeicons/tick02.jsx').default
  const IHugeiconsZap: typeof import('~icons/hugeicons/zap.jsx').default
  const ILucideActivity: typeof import('~icons/lucide/activity.jsx').default
  const ILucideCode2: typeof import('~icons/lucide/code2.jsx').default
  const ILucideFileJson: typeof import('~icons/lucide/file-json.jsx').default
  const ILucideGhost: typeof import('~icons/lucide/ghost.jsx').default
  const ILucideGitCompare: typeof import('~icons/lucide/git-compare.jsx').default
  const ILucideTable: typeof import('~icons/lucide/table.jsx').default
  const ILucideZap: typeof import('~icons/lucide/zap.jsx').default
  const Link: typeof import('react-router-dom').Link
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const Suspense: typeof import('react').Suspense
  const ThemeProviderContext: typeof import('./hooks/use-theme').ThemeProviderContext
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('./lib/utils').cn
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebounce: typeof import('./hooks/use-debounce').useDebounce
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEditor: typeof import('./hooks/use-editor').useEditor
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFont: typeof import('./hooks/use-editor').useFont
  const useGoBack: typeof import('./hooks/use-go-back').default
  const useHead: typeof import('@unhead/react').useHead
  const useHeadSafe: typeof import('@unhead/react').useHeadSafe
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useJSONEditor: typeof import('./hooks/use-json-editor').useJSONEditor
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useSeo: typeof import('./hooks/use-seo').useSeo
  const useSeoMeta: typeof import('@unhead/react').useSeoMeta
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTheme: typeof import('./hooks/use-theme').useTheme
  const useTransition: typeof import('react').useTransition
  const useUnhead: typeof import('@unhead/react').useUnhead
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EditorTheme, MonoFont, EditorFontSize } from './hooks/use-editor'
  import('./hooks/use-editor')
  // @ts-ignore
  export type { JSONPrimitive, JSONValue, JSONError } from './hooks/use-json-editor'
  import('./hooks/use-json-editor')
  // @ts-ignore
  export type { Theme, ThemeProviderState } from './hooks/use-theme'
  import('./hooks/use-theme')
}
